name: complete_health_agi
description: A full-featured Health AGI Flutter App with OpenAI integration, voice input/output, charts, notifications, and personalized health plans.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP for OpenAI API calls
  http: ^1.1.0

  # Text-to-Speech
  flutter_tts: ^3.5.0

  # Speech-to-Text for voice input
  speech_to_text: ^6.6.2

  # Charts for Health Analytics
  charts_flutter: ^0.12.0

  # Local notifications
  flutter_local_notifications: ^14.0.0

  # State management
  provider: ^6.0.6

  # Date & time formatting (compatible version)
  intl: ^0.17.0

  # Optional: store user preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
